# source: https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/resnet_k8s.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: resnet-deployment
spec:
  selector:
    matchLabels:
      app: resnet-server
  replicas: 3
  template:
    metadata:
      labels:
        app: resnet-server
    spec:
      containers:
      - name: resnet-container
        image: gcr.io/tensorflow-serving/resnet
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: resnet-service
  name: resnet-service
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: resnet-server
  type: LoadBalancer