FROM tensorflow/serving

COPY ./tmp/mobilenet /models/mobilenet

ENV MODEL_NAME mobilenet
ENV PORT 5000

# config: https://www.tensorflow.org/tfx/serving/serving_config
CMD [ "--rest_api_port=5000" ]
