apiVersion: v1
kind: Service
metadata:
  labels:
    app: iris-classifier
  name: iris-classifier
  namespace: bentoml
spec:
  ports:
  - name: predict
    port: 5000
    targetPort: 5000
  selector:
    app: iris-classifier
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iris-classifier
  name: iris-classifier
  namespace: bentoml
spec:
  selector:
    matchLabels:
      app: iris-classifier
  template:
    metadata:
      labels:
        app: iris-classifier
    spec:
      containers:
      - image: ghcr.io/nimamahmoudi/bentoml-iris-classifier:20210429200418
        imagePullPolicy: IfNotPresent
        name: iris-classifier
        command:
          - "--workers=2"
        ports:
        - containerPort: 5000
